### ISSUE TITLE
mihomo 内核设置为自定义uidgid后 setcap 并未使 mihomo 正常工作

### ISSUE THREAD

**Issue by hour-keeper** [CHIZI-0618/box4magisk#104]
通过kernelsu的.rw功能将/system挂载为可读写可持久存储后把mihomo内核移入/system/bin目录，在默认的`root:net_admin`uidgid，以及`proxy_mode="core"`下正常工作，但一旦将uid改为0以外的值就出现mihomo无法自己开启tun的问题，把原来代码下https://github.com/CHIZI-0618/box4magisk/blob/2d0801a132ec229c74b43853cc77aea5d48156f8/box/scripts/box.service#L53
替换成从 https://github.com/MetaCubeX/mihomo/issues/961 抄的`CAP_NET_ADMIN,CAP_NET_RAW,CAP_NET_BIND_SERVICE,CAP_SYS_TIME,CAP_SYS_PTRACE,CAP_DAC_READ_SEARCH=ep`后，运行 /data/adb/box/scripts/box.service restart不报错，但仍然无法开启tun

**Comment by hour-keeper** [comment]
```yaml
tun:
  enable: true
  stack: system
  dns-hijack:
    - 'any:53'
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  strict-route: true
  exclude-package:
  - org.mewx.wenku8
```
tun相关设置
