### ISSUE TITLE
连接wifi时能正常代理，流量下只有tg app走了代理

### ISSUE THREAD

**Issue by cfandora** [CHIZI-0618/box4magisk#7]
核心为[clash meta](https://github.com/MetaCubeX/Clash.Meta/releases/tag/Prerelease-Alpha)，配置如下(已去除节点和规则)

[clash.txt](https://github.com/CHIZI-0618/box4magisk/files/10528839/clash.txt)

代理方式为TProxy，系统为Android 13

使用流量时也正确检测到了rmnet_data3，但实际使用只有tg app走了代理，chrome甚至也没走代理，请问该如何解决？需要补充哪些信息？

**Comment by CHIZI-0618** [comment]
我注意到你提供的配置文件 clash.txt 有以下内容：
  
```yaml
redir-port: 7893
tproxy-port: 7894

tun:
  enable: true
  stack: system # or gvisor
  dns-hijack:
    - 'any:53'
  auto-route: true
  auto-detect-interface: true
```

此时 Clash.Meta 内核的 tun 入站已打开且开启了自动路由(`auto-route: true`)，这会与脚本的 Tproxy 模式路由冲突。

根据已知信息
解决方法为
  
一. 修改 Clash.Meta 配置

1. 关闭 Clash.Meta 的 tun 入站，即

```yaml
tun:
  enable: false
  stack: system # or gvisor
  dns-hijack:
    - 'any:53'
  auto-route: false
  auto-detect-interface: false
```

2. tproxy 入站与 dns 监听是必要的，即

```yaml
tproxy-port: 1536

dns:
  enable: true
  listen: 0.0.0.0:1053
```
&emsp;注意端口值要与 box.config 中的定义一致 https://github.com/CHIZI-0618/box4magisk/blob/603b13a4130923c90830943c27dc36f6702b4c20/box/scripts/box.config#L6-L7

二. 修改 box.config 配置

1. 使用 Clash 内核 Tproxy 代理即
```shell
bin_name="clash"
proxy_method="TPROXY"
```
2. 重新运行 box 服务与 tproxy 脚本
在任意终端执行以下命令

```shell
su
/data/adb/box/scripts/box.service restart
/data/adb/box/scripts/box.tproxy renew
```
  
  
此时即可使用 clash 内核启动透明代理
