### ISSUE TITLE
怎么在使用fake-ip的同时支持包名黑/白名单？

### ISSUE THREAD

**Issue by yqs112358** [CHIZI-0618/box4magisk#74]
如题，目前使用mihomo最新Release版本

首先尝试裸tproxy不开黑白名单，enhance_mode使用fake-ip，box完全可以正常工作。不过系统中所有应用都会走代理
然后尝试开包名白名单，开了之后应用就连不上mihomo了。查了一下issue似乎说是tproxy黑白名单和fake-ip不兼容？

然后尝试方案2，把proxy_mode设置成core，clash配置文件中打开tun，在配置文件中用include-package设置包名白名单，然后启动box，发现应用仍然连不上mihomo。

很好奇：
1. 为啥tproxy黑白名单与fake-ip不兼容捏
2. 有没有什么办法可以在使用fake-ip的同时支持包名黑白名单？
方案2的tun+include-package有啥问题吗，为什么也不能工作呢🤔

配置文件编写应该没有问题

**Comment by yqs112358** [comment]
方案2 配置文件部分：
```
tun:
  enable: true
  stack: system
  dns-hijack:
    - "0.0.0.0:53"
    - "tcp://0.0.0.0:53"
  auto-detect-interface: true   # 自动识别出口网卡
  strict-route: true            # 严格路由模式
  gso: true                     # 启用通用分段卸载（仅Linux）
  auto-route: true              # 自动配置路由表
  # 安卓代理包名白名单
  include-package:
    - "com.microsoft.office.outlook"
    - "com.android.vending"
    - "com.openai.chatgpt"
    - "com.github.android"
    - "com.google.ar.core"
    - ......

dns:
  enable: true
  use-hosts: true
  use-system-hosts: true
  listen: 0.0.0.0:1053        # DNS监听地址
  ipv6: false

  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/16
  fake-ip-filter:       # fake ip 白名单列表
    - "*.lan"
    - "*.local"
    # Xiaomi
    - "+.market.xiaomi.com"
    # Windows Connnect Detection	
    - "*.msftconnecttest.com"	
    - "*.msftncsi.com"
  fake-ip-filter-mode: blacklist
  
  default-nameserver:
    - "223.5.5.5"
  proxy-server-nameserver:
    - "https://223.5.5.5/dns-query"   # 阿里 DoH DNS
    - "https://1.12.12.12/dns-query"  # 腾讯 DoH DNS
  nameserver:
    - "system"          # 本地DNS
    - "dhcp://system"
    - "223.5.5.5"       # 阿里DNS
    - "180.76.76.76"    # 百度DNS
    - "119.29.29.29"    # 腾讯DNS
  fallback:
    - "tls://1.1.1.1#Proxy"   # CF DoT DNS
    - "tls://8.8.8.8#Proxy"   # Google DoT DNS
  fallback-filter:
    geoip: true       # 默认
    geoip-code: CN
    ipcidr: # 在这个网段内的 IP 地址会被考虑为被污染的 IP
      - 240.0.0.0/4
```

**Comment by CHIZI-0618** [comment]
安卓应用的 DNS 最终由 netd 负责，tproxy 模式的黑白名单由 iptables uid 扩展匹配进行
黑名单应用的 DNS 仍会被 box 核心劫持返回 fakeip，所以黑名单无法上网，使用 singbox 的 dns rule 控制黑名单应用域名返回非 fakeip dns 可以缓解上述问题，mihomo 可以考虑使用 fake-ip-filter，目前该字段已支持 规则集合而不止单域名写法

至于你说的方案二，sing-tun 理论可行，当然我没有试过，我没用过 tun，我不清楚你失败的原因

**Comment by yqs112358** [comment]
> 安卓应用的 DNS 最终由 netd 负责，tproxy 模式的黑白名单由 iptables uid 扩展匹配进行
> 黑名单应用的 DNS 仍会被 box 核心劫持返回 fakeip，所以黑名单无法上网，使用 singbox 的 dns rule 控制黑名单应用域名返回非 fakeip dns 可以缓解上述问题，mihomo 可以考虑使用 fake-ip-filter，目前该字段已支持 规则集合而不止单域名写法
> 
> 至于你说的方案二，sing-tun 理论可行，当然我没有试过，我没用过 tun，我不清楚你失败的原因

感谢大佬🥰我再研究研究

**Comment by yqs112358** [comment]
排查出来应该是没在tun设置里面指定device的锅🤣现在工作正常了，把device设置成和config里面一个名字

**Comment by NiuHK** [comment]
> 排查出来应该是没在tun设置里面指定device的锅🤣现在工作正常了，把device设置成和config里面一个名字

所以现在有办法同时开fake-ip和黑白名单吗，我用的151版本，貌似黑白名单会自动设置为redir-host

**Comment by yqs112358** [comment]
> 所以现在有办法同时开fake-ip和黑白名单吗，我用的151版本，貌似黑白名单会自动设置为redir-host

可以。首先在模块配置里面选"core"模式，也就是用mihomo自带的tun
然后改mihomo配置，把tun打开，配置条目写好，用`include-package`声明安卓包名白名单
如果要用黑名单，改用`exclude-package`就行

示例配置：
```
find-process-mode: always
...
tun:
  enable: true
  stack: system
  device: tun1
  dns-hijack:
    - "0.0.0.0:53"
    - "tcp://0.0.0.0:53"
  auto-detect-interface: true   # 自动识别出口网卡
  strict-route: true            # 严格路由模式
  gso: true                     # 启用通用分段卸载（仅Linux）
  auto-route: true              # 自动配置路由表
  # 安卓代理包名白名单
  include-package:
    - "com.microsoft.office.outlook"
    - "com.android.vending"
    - "com.openai.chatgpt"
    - "com.github.android"
    - ......
```
