### ISSUE TITLE
为什么只要替换掉proxy-groups和rules部分的内容，就会无法访问谷歌呢？

### ISSUE THREAD

**Issue by LibraStalker** [CHIZI-0618/box4magisk#75]
我替换的内容如下所示：
```
proxies:
  - name: "直连"
    type: direct
    udp: true
  - name: "DNS"
    type: dns
  - name: "阿里云新加坡服务器"
    type: trojan
    server: 我自己搭建的节点
    port: 443
    password: **********
    udp: true
    skip-cert-verify: true
    alpn:
      - h2
      - http/1.1

#这里是订阅更新和延迟测试相关
#可以更改 proxy 指定的出站
p: &p {type: http, interval: 86400, proxy: DIRECT, header: {User-Agent: ["Clash.Meta/mihomo/Alpha/1.18.6"]}, health-check: {enable: true, url: https://cp.cloudflare.com, interval: 18000, lazy: true}}

# url 里填写自己的订阅,名称不能重复
proxy-providers:
  provider1:
    <<: *p
    url: "********"
    path: ./proxy_providers/yiyuan.yaml

  # provider2:
  #   <<: *p
  #   url: ""

proxy-groups:
  - name: 默认
    type: select
    proxies: [自动选择,直连,香港,台湾,日本,新加坡,美国,其它地区]

  - name: 自动选择
    type: url-test
    include-all: true
    tolerance: 10

  #分隔,下面是地区分组
  - name: 香港
    type: select
    include-all: true
    filter: "(?i)港|hk|hongkong|hong kong"

  - name: 台湾
    type: select
    include-all: true
    filter: "(?i)台|tw|taiwan"

  - name: 日本
    type: select
    include-all: true
    filter: "(?i)日|jp|japan"

  - name: 美国
    type: select
    include-all: true
    filter: "(?i)美|us|unitedstates|united states"

  - name: 新加坡
    type: select
    include-all: true
    filter: "(?i)(新|sg|singapore)"

  - name: 其它地区
    type: select
    include-all: true
    filter: "(?i)^(?!.*(?:🇭🇰|🇯🇵|🇺🇸|🇸🇬|🇨🇳|港|hk|hongkong|台|tw|taiwan|日|jp|japan|新|sg|singapore|美|us|unitedstates)).*"
    
rules:
  - AND,((NETWORK,UDP),(DST-PORT,123)),DIRECT
  - GEOSITE,biliintl,默认
  - GEOSITE,ehentai,默认
  - GEOSITE,github,默认
  - GEOSITE,twitter,默认
  - GEOSITE,youtube,默认
  - GEOSITE,google,默认
  - GEOSITE,telegram,默认
  - GEOSITE,netflix,默认
  - GEOSITE,bilibili,默认
  - GEOSITE,bahamut,默认
  - GEOSITE,spotify,默认

  - GEOIP,google,默认
  - GEOIP,netflix,默认
  - GEOIP,telegram,默认
  - GEOIP,twitter,默认
  - GEOSITE,CN,直连
  - GEOIP,CN,直连
  - GEOIP,PRIVATE,DIRECT,no-resolve
  - MATCH,默认
``` 
因为我要添加一个自己搭建的节点，实测将rules部分的对应的代理组换成自己配置的“默认”代理组，访问谷歌就会提示“你的连接不是专用连接”，不知道是什么原因。
