### ISSUE TITLE
关于tun_device & fswatch: watcher removed

### ISSUE THREAD

**Issue by Moecg** [CHIZI-0618/box4magisk#79]
一直有一个问题，使用mihomo核心后，开启tun并且在mihomo的config.yaml中修改device为```xxx```，需要同步更改```scripts/box.config```line 12中的```tun_device="tun0"```为```tun_device="xxx"```吗

---

另外在日志中看到```fswatch: watcher removed: /data/system/packages.xml```是配置有什么问题吗（不影响使用，可以不管）
```
time="2024-09-28T00:50:32.19553288+08:00" level=info msg="Start initial configuration in progress"
time="2024-09-28T00:50:32.196632932+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-09-28T00:50:32.196647776+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-09-28T00:50:32.196949807+08:00" level=info msg="Initial configuration complete, total time: 1ms"
time="2024-09-28T00:50:32.262483713+08:00" level=warning msg="[TUN] default interface changed by monitor,  => wlan0"
time="2024-09-28T00:51:06.077756825+08:00" level=error msg="fswatch: watcher removed: /data/system/packages.xml"
```

```yaml
mixed-port: 7890
tproxy-port: 1536
ipv6: false
allow-lan: false
mode: rule
log-level: warning

unified-delay: false
tcp-concurrent: true
external-controller: 127.0.0.1:9090
external-ui: ui/metacubexd
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

find-process-mode: always
#global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: false
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

tun:
  enable: true
  stack: system
  device: wlan2
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: false
  auto-detect-interface: true
  strict-route: true

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/15
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "+.market.xiaomi.com"
    - "rule-set:fakeip-filter"
  fake-ip-filter-mode: blacklist
  default-nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  nameserver:
    - https://dns.cloudflare.com/dns-query
    - https://dns.google/dns-query
  nameserver-policy:
    "rule-set:google-cn_domain":
      - https://dns.cloudflare.com/dns-query
      - https://dns.google/dns-query
    "rule-set:cn_domain,private_domain":
      - https://120.53.53.53/dns-query
      - https://223.5.5.5/dns-query

```
