### ISSUE TITLE
all DNS requests failed

### ISSUE THREAD

**Issue by fievell** [CHIZI-0618/box4magisk#8]
使用 clash.meta 1.14.1 core

无法连接网络，log中所有连接均报错如下
`time="2023-02-11T06:45:58Z" level=warning msg="[TCP] dial PROXY (match RuleSet/proxy) x.x.x.x:58272 --> duckduckgo.com:443 error: csunicom.nodenet.cloud:28881 connect error: all DNS requests failed, first error: dial tcp4 94.140.15.15:53: no such device"
`

config.yaml

```
tproxy-port: 1536
allow-lan: true
mode: rule
log-level: debug
ipv6: false
external-controller: 127.0.0.1:9999
external-ui: Dashboard
geodata-mode: true

profile:
  store-selected: true
  store-fake-ip: false

tun:
  enable: false
  stack: system # or gvisor
  dns-hijack:
    - 'any:53'
  auto-route: true
  auto-detect-interface: true

hosts:
  '+.clash.meta': 127.0.0.1

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip 
  fake-ip-filter: ['connect.rom.miui.com', '+.gstatic.com', '*', '+.lan', '+.stun.*.*', '+.stun.*.*.*', '+.stun.*.*.*.*', '+.stun.*.*.*.*.*', 'lens.l.google.com', '*.mcdn.bilivideo.cn']
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
    - 'https://223.5.5.5/dns-query'
    - 'https://1.12.12.12/dns-query'
  nameserver:
    - 114.114.114.114
    - 8.8.8.8
    - 'https://223.5.5.5/dns-query'   # alidns
    - 'https://1.12.12.12/dns-query'   # dns.pub
  fallback:
    - 'tcp://185.222.222.222#Proxy'  # dns.sb
    - 'tcp://94.140.15.15#Proxy'     # adguard
    - 'tcp://8.8.4.4#Proxy'          # google
  fallback-filter:
    geoip: false
    geoip-code: CN
    geosite:
      - '!CN'
#      - GFW
#      - GREATFIRE
#    domain:
#      - '+.gstatic.com'
```

box.config

```
#!/system/bin/sh

bin_name="clash"

tproxy_port="1536"
clash_dns_port="1053"
clash_dns_listen="0.0.0.0:1053"
clash_fake_ip_range="198.18.0.1/16"

box_user_group="root:net_admin"
# If you want to change the user or group, you must make the Box core in the /system/bin directory, otherwise the changes will not take effect.
# If you are using Magisk, you can copy the Box core files (sing-box, clash, etc.) to /data/adb/modules/bin_files/system/bin/ and reboot the phone
bin_name_list=("sing-box" "clash" "xray" "v2ray")
box_path="/data/adb/box"
bin_path="${box_path}/bin/${bin_name}"
run_path="${box_path}/run"
pid_file="${run_path}/${bin_name}.pid"


intranet=(0.0.0.0/8 10.0.0.0/8 100.64.0.0/10 127.0.0.0/8 169.254.0.0/16 192.0.0.0/24 192.0.2.0/24 192.88.99.0/24 192.168.0.0/16 198.51.100.0/24 203.0.113.0/24 224.0.0.0/4 240.0.0.0/4 255.255.255.255/32)
intranet6=(::/128 ::1/128 ::ffff:0:0/96 100::/64 64:ff9b::/96 2001::/32 2001:10::/28 2001:20::/28 2001:db8::/32 2002::/16 fe80::/10 ff00::/8)

ipv6="disable"

proxy_method="TPROXY"
# REDIRECT: TCP only / TPROXY: TCP + UDP / MIXED: REDIRECT TCP + TUN UDP

proxy_mode="blacklist"
# blacklist / whitelist / core
user_packages_list=()
# Android User:Package Name, For example:
# user_packages_list=("0:com.android.captiveportallogin" "10:com.tencent.mm")

ap_list=("wlan+" "ap+" "rndis+")
ignore_out_list=()

```
