### ISSUE TITLE
IPv6 关闭在 WiFi 打开关闭后失效，导致 DNS 请求绕过 mihomo DNS模块

### ISSUE THREAD

**Issue by nyanyacoffee** [CHIZI-0618/box4magisk#88]
以下问题在使用TPROXY TUN模式下，结果相同

IPv6配置为关闭下，如果打开关闭WiFi就会失效
而在 WiFi 环境下 IPv6 启用时，DNS 请求会绕过 mihomo 的 DNS 模块，从不知名的地方跑出去
但在使用移动数据时未出现此问题
造成无法正常使用DNS进行域名分流
在配置文件中包含以下配置也无法解决
```yaml
proxies:
  - name: "DNS_Hijack"
    type: dns
rules:
  - DST-PORT,53,DNS_Hijack
```
奇奇怪怪的问题，或许是系统的锅?
- 系统信息
MI HyperOS1 A14
Kernel: Pandora 5.10 r1
